# -*- coding: utf-8 -*-
"""Make A List Of Paths To All Folders Where You Have Data
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1jP0Et9_wZkyLz6N_i6GRMGasAdIiKBA0
"""

dirName = 'dirName = C:\Augmented Data'
folders = listdir(dirName)

def getListOfFiles(dirName):
    listOfFile = os.listdir(dirName)
    allFiles = list()
    for fol name in listOfFile:
        fullPath = os.path.join(dirName,fol_name)
        allFiles.append(fullPath)
    return allFiles

Folders = getListOfFiles(dirName)
len(Folders)
subfolders = []
for num in range(len(Folders)):
    sub_fols = getListOfFiles(Folders[num])
    subfolders+=sub_fols
subfolders